// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxydxswrmpkspvbdbckd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4eWR4c3dybXBrc3B2YmRiY2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NzYzMjUsImV4cCI6MjA1NzI1MjMyNX0.qY3yCnxXpmOPiblbWeIhOjIaDMQVpkSi6SjDWOgZho4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);